import Navbar from "@/components/shared/navbar";
import BackgroundTexture from "@/components/style-componenets/bg-texture";
import { auth } from "@/lib/auth";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { headers } from "next/headers";
import { Toaster } from "sonner";
// @ts-ignore
import "./globals.css";

const dmSans = DM_Sans({
  weight: ["400", "500"],
  variable: "--font-dm-mono-sans",
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased relative`}>
        {/* Background textures and gradients */}
        <Navbar session={session} />
        {children}
        <BackgroundTexture />
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
