import BackgroundTexture from "@/components/pages/home/bg-texture";
import Navbar from "@/components/shared/navbar";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({
  weight: ["400", "500"],
  variable: "--font-dm-mono-sans",
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased relative`}>
        {/* Background textures and gradients */}
        <Navbar />
        {children}
        <BackgroundTexture />
      </body>
    </html>
  );
}
